# Generated by Django 3.2.7 on 2021-09-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20210929_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('floor_number', models.IntegerField(default=1)),
                ('room_number', models.IntegerField()),
            ],
        ),
    ]
